services:
  redis:
    image: redis:7-alpine
    container_name: masv2-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6380:6379"
    volumes:
      - ./redis_data:/data
