services:
  qdrant:
    image: qdrant/qdrant:gpu-nvidia-latest
    container_name: masv2-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      QDRANT__GPU__INDEXING: "1"
      QDRANT__LOG_LEVEL: "info"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
