services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: masv2-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      QDRANT__LOG_LEVEL: "info"
