services:
  prometheus:
    image: prom/prometheus:latest
    container_name: masv2-prom
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9091:9090"   # host 9091 -> container 9090

  grafana:
    image: grafana/grafana:latest
    container_name: masv2-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_storage:/var/lib/grafana
