services:
  prometheus:
    image: prom/prometheus:latest
    container_name: obs-prom
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prom-data:/prometheus
    ports: ["9090:9090"]

  loki:
    image: grafana/loki:latest
    container_name: obs-loki
    restart: unless-stopped
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/config.yml
      - ./loki-data:/loki
    ports: ["3100:3100"]

  grafana:
    image: grafana/grafana:latest
    container_name: obs-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./dashboards:/var/lib/grafana/dashboards
    ports: ["3000:3000"]